name: textlint

on:
  pull_request:
    paths: ['docs/articles/**/*.md']

jobs:
  textlint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Switch to pull request branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install textlint
        run: >
            npm install --save-dev \
              textlint \
              textlint-filter-rule-allowlist \
              textlint-rule-preset-ja-technical-writing
      - name: Install packages
        run: npm install
      - name: Run textlint
        run: npx textlint "docs/articles/**/*.md" -o ./.textlint.log | true
        shell: bash {0}
      - name: generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with: 
          app_id: ${{ secrets.TEXTLINT_APPID}}
          private_key: ${{secrets.TEXTLINT_KEY}}
      - name: Report problems
        run: |
          if [ -e ./.textlint.log ]; then
            # create body file
            pwd_esc=$(pwd | sed 's/\//\\\//g')
            cat ./.textlint.log | sed "s/${pwd_esc}/### :policeman: ./g" >> ./.body.txt
            # pr comment
            gh pr comment --body-file ./.body.txt "${URL}"
          fi
        env:
           GH_TOKEN : ${{ steps.generate_token.outputs.token }}
